### ISSUE TITLE
spatie/shiki-php requires php 8.0

### ISSUE THREAD

**Issue by zsoltjanes** [ueberdosis/tiptap-php#18]
Hi, The spatie/shiki-php package requires php 8.0 but I would like to use the package in php 7.4 so right now I cant use this package. Do you have a workaround for this?

**Comment by hanspagel** [comment]
The README has this in the installation section:

> PHP 7.4 support: The package should work with PHP 7.4, but it requires spatie/shiki-php which requires PHP 8.0. You can still install the package though, if you pass --ignore-platform-reqs. You just won’t be able to use the CodeBlockShiki node then.

I don’t have an idea how we could workaround this. If someone knows how to do better, I’m happy to incorporate the required changes!
