### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by reefki** [ueberdosis/tiptap-php#25]
Hi there,

Silly question but when I trying to get JSON from the following HTML, it throws `Array to string conversion in ../vendor/ueberdosis/tiptap-php/src/Core/DOMParser.php on line 144`.

```
<p><iframe frameborder="0" height="385" src="https://www.youtube.com/embed/xxx" width="590"></iframe></p>
<p><iframe frameborder="0" height="385" src="https://www.youtube.com/embed/yyy" width="590"></iframe></p>
```

**Comment by anonim1133** [comment]
Have you been able to find out what was the reason of that? Have you got it fixed?

**Comment by robertdrakedennis** [comment]
ive also started having this issue, no real leads on whats causing it, i was migrating away from the deprecated tiptap parser but i definitely cant unless i get more info on how this is occuring

**Comment by Somethingideally** [comment]
Same issue

**Comment by scottmetoyer** [comment]
I'm also experiencing this issue.

**Comment by marvinosswald** [comment]
Very weird, happens to me on production but not locally same php version tho.

PHP: 8.2.5

**Comment by godismyjudge95** [comment]
I just encountered this while attempting to import content from WordPress - it wraps everything in p tags.

Submitted a PR with a failing test, so hopefully it gets merged soon 🤞

**Comment by enkay** [comment]
I'm also getting this error while parsing html, no idea what's triggering it.

On version 1.3.0

**Comment by marvinosswald** [comment]
@enkay I'm now quite certain this is caused by the `p` tag surrounding the image.
